// <auto-generated />
using System;
using Clearfolio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clearfolio.Api.Migrations
{
    [DbContext(typeof(ClearfolioDbContext))]
    [Migration("20260315122658_AddInvestmentBondAssetType")]
    partial class AddInvestmentBondAssetType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Clearfolio.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_type_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AUD")
                        .HasColumnName("currency");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double>("JointSplit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5)
                        .HasColumnName("joint_split");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerMemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_member_id");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("sole")
                        .HasColumnName("ownership_type");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("OwnerMemberId");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Clearfolio.Api.Models.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("GrowthClass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("growth_class");

                    b.Property<bool>("IsCgtExempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_cgt_exempt");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_super");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<string>("Liquidity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("liquidity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("asset_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Category = "cash",
                            GrowthClass = "defensive",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "immediate",
                            Name = "Cash — savings / transaction",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Category = "cash",
                            GrowthClass = "defensive",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "short_term",
                            Name = "Cash — term deposit (≤90 days)",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Category = "cash",
                            GrowthClass = "defensive",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "long_term",
                            Name = "Term deposit (>90 days)",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Category = "investable",
                            GrowthClass = "growth",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "short_term",
                            Name = "Australian shares / ETFs",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Category = "investable",
                            GrowthClass = "growth",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "short_term",
                            Name = "International shares / ETFs",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Category = "investable",
                            GrowthClass = "defensive",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "short_term",
                            Name = "Bonds / fixed income",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Category = "investable",
                            GrowthClass = "growth",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "immediate",
                            Name = "Cryptocurrency",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            Category = "investable",
                            GrowthClass = "growth",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "short_term",
                            Name = "Investment bond",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Category = "retirement",
                            GrowthClass = "mixed",
                            IsCgtExempt = false,
                            IsSuper = true,
                            IsSystem = true,
                            Liquidity = "restricted",
                            Name = "Superannuation — Accumulation",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Category = "retirement",
                            GrowthClass = "mixed",
                            IsCgtExempt = false,
                            IsSuper = true,
                            IsSystem = true,
                            Liquidity = "long_term",
                            Name = "Superannuation — Pension phase",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            Category = "property",
                            GrowthClass = "growth",
                            IsCgtExempt = true,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "long_term",
                            Name = "Primary residence (PPOR)",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            Category = "property",
                            GrowthClass = "growth",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "long_term",
                            Name = "Investment property",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            Category = "other",
                            GrowthClass = "defensive",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "long_term",
                            Name = "Vehicle",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            Category = "other",
                            GrowthClass = "mixed",
                            IsCgtExempt = false,
                            IsSuper = false,
                            IsSystem = true,
                            Liquidity = "long_term",
                            Name = "Other physical asset",
                            SortOrder = 14
                        });
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AUD")
                        .HasColumnName("base_currency");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PreferredPeriodType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("FY")
                        .HasColumnName("preferred_period_type");

                    b.HasKey("Id");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Clearfolio.Api.Models.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("MemberTag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("member_tag");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Liability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AUD")
                        .HasColumnName("currency");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double>("JointSplit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5)
                        .HasColumnName("joint_split");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<Guid>("LiabilityTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("liability_type_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerMemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_member_id");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("sole")
                        .HasColumnName("ownership_type");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LiabilityTypeId");

                    b.HasIndex("OwnerMemberId");

                    b.HasIndex("HouseholdId", "IsActive");

                    b.ToTable("liabilities", (string)null);
                });

            modelBuilder.Entity("Clearfolio.Api.Models.LiabilityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("DebtQuality")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("debt_quality");

                    b.Property<bool>("IsHecs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_hecs");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("liability_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Category = "mortgage",
                            DebtQuality = "neutral",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Home loan — PPOR",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Category = "mortgage",
                            DebtQuality = "productive",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Home loan — Investment property",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Category = "personal",
                            DebtQuality = "bad",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Personal loan",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Category = "personal",
                            DebtQuality = "bad",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Car loan",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Category = "credit",
                            DebtQuality = "bad",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Credit card",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Category = "student",
                            DebtQuality = "neutral",
                            IsHecs = true,
                            IsSystem = true,
                            Name = "HECS / HELP debt",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Category = "personal",
                            DebtQuality = "productive",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Margin loan",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Category = "tax",
                            DebtQuality = "neutral",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Tax liability",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Category = "other",
                            DebtQuality = "neutral",
                            IsHecs = false,
                            IsSystem = true,
                            Name = "Other liability",
                            SortOrder = 9
                        });
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("AUD")
                        .HasColumnName("currency");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT")
                        .HasColumnName("household_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("period");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RecordedBy");

                    b.HasIndex("EntityId", "Period");

                    b.HasIndex("HouseholdId", "Period");

                    b.ToTable("snapshots", (string)null);
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Asset", b =>
                {
                    b.HasOne("Clearfolio.Api.Models.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clearfolio.Api.Models.Household", "Household")
                        .WithMany("Assets")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clearfolio.Api.Models.HouseholdMember", "OwnerMember")
                        .WithMany()
                        .HasForeignKey("OwnerMemberId");

                    b.Navigation("AssetType");

                    b.Navigation("Household");

                    b.Navigation("OwnerMember");
                });

            modelBuilder.Entity("Clearfolio.Api.Models.HouseholdMember", b =>
                {
                    b.HasOne("Clearfolio.Api.Models.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Liability", b =>
                {
                    b.HasOne("Clearfolio.Api.Models.Household", "Household")
                        .WithMany("Liabilities")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clearfolio.Api.Models.LiabilityType", "LiabilityType")
                        .WithMany("Liabilities")
                        .HasForeignKey("LiabilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clearfolio.Api.Models.HouseholdMember", "OwnerMember")
                        .WithMany()
                        .HasForeignKey("OwnerMemberId");

                    b.Navigation("Household");

                    b.Navigation("LiabilityType");

                    b.Navigation("OwnerMember");
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Snapshot", b =>
                {
                    b.HasOne("Clearfolio.Api.Models.Household", "Household")
                        .WithMany("Snapshots")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clearfolio.Api.Models.HouseholdMember", "RecordedByMember")
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("RecordedByMember");
                });

            modelBuilder.Entity("Clearfolio.Api.Models.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Clearfolio.Api.Models.Household", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Liabilities");

                    b.Navigation("Members");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Clearfolio.Api.Models.LiabilityType", b =>
                {
                    b.Navigation("Liabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
